apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-herrera-deployment
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-herrera
  template:
    metadata:
      labels:
        app: producer-herrera
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: producer
                    operator: In
                    values:
                      - herrera
      containers:
        - name: producer-herrera-container
          image: herreran/producer-herrera:latest
          ports:
            - containerPort: 5000
          env:
            - name: KAFKA_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: kafka_address
            - name: TOPIC_NAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: topic_name
---
apiVersion: v1
kind: Service
metadata:
  name: producer-herrera-service
spec:
  selector:
    app: producer-herrera
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30100
  type: NodePort
